service: a-safe-space
provider:
  name: aws
  runtime: python3.6
  profile:
  environment:
    TELEGRAM_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, '1846154865:AAFfRczgPFIX-x5dou3Embu-y-8YsofIDHs'}

functions:
  webhook:
    handler: handler.webhook
    events:
      - http: POST /

  set_webhook:
    handler: handler.set_webhook
    events:
      - http: POST /set_webhook

plugins:
  - serverless-python-requirements
